# Generated by Django 4.2.29 on 2026-04-03 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('chatgpt', 'ChatGPT'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('other', 'Other')], default='manual', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('content', 'Content'), ('coding', 'Coding'), ('business', 'Business'), ('learning', 'Learning'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('reuse_count', models.PositiveIntegerField(default=0)),
                ('outcome_metric', models.CharField(blank=True, choices=[('views', 'Views'), ('clicks', 'Clicks'), ('leads', 'Leads'), ('revenue', 'Revenue'), ('time_saved', 'Time Saved'), ('other', 'Other')], max_length=20)),
                ('outcome_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='prompts_pro_user_id_6fdc10_idx'), models.Index(fields=['user', 'category'], name='prompts_pro_user_id_659f13_idx'), models.Index(fields=['user', '-score'], name='prompts_pro_user_id_270067_idx'), models.Index(fields=['user', '-rating'], name='prompts_pro_user_id_fc89a1_idx')],
            },
        ),
    ]
