# Generated by Django 4.2.29 on 2026-04-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow this prompt to be visible on the public Explore page'),
        ),
    ]
