# Generated by Django 4.2.29 on 2026-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='outcome_metric',
            field=models.CharField(blank=True, choices=[('tasks_completed', 'Tasks Completed'), ('quality_score', 'Quality Score'), ('accuracy', 'Accuracy'), ('user_satisfaction', 'User Satisfaction'), ('cost_saved', 'Cost Saved'), ('time_saved', 'Time Saved'), ('revenue', 'Revenue Impact'), ('views', 'Views / Reach'), ('clicks', 'Action Clicks'), ('leads', 'Lead Generation'), ('other', 'Custom Metric')], max_length=20),
        ),
    ]
